# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       pgz-spaceinvaders-qt5

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Space Invaders Clone
Version:    0.8
Release:    1
Group:      Games/Action
License:    GPL v2
URL:        http://www.piggz.co.uk
Source0:    %{name}-%{version}.tar.bz2
Source100:  pgz-spaceinvaders-qt5.yaml
Requires:   Qt5Declarative
Requires:   Qt5Multimedia
Requires:   qt5-qtsvg
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(qdeclarative5-boostable)
BuildRequires:  pkgconfig(Qt5Svg)

%description
Space Invaders clone written using QML


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
/usr/bin
/usr/share/pgz-spaceinvaders-qt5
/usr/share/applications
# >> files
# << files
